# SPDX-FileCopyrightText: 2020 Max Reznik <reznikmm@gmail.com>
#
# SPDX-License-Identifier: MIT
#

version: 2
jobs:
   build:
     docker:
       - image: reznik/oasis-build:fc30.02
     steps:
       - checkout
       - run: make -j2 check
